name: needle
channels:
  - defaults
dependencies:
  - pip=23.3.1
  - python=3.10.15
  - pip:
      - accelerate==0.30.0
      - torch==2.2.1
      - transformers==4.38.2
      - openai==1.33.3
      - tiktoken==0.6.0
      - sentencepiece==0.2.0